---
title: "RECINTOS QUE PRESENTARON ANOMALÍAS"
output: 
  flexdashboard::flex_dashboard:
    
    vertical_layout: fill
    navbar:
    - {icon: "fa-share-alt", href: "https://www.aru.org.bo/", align: right}  
    - {icon: "fa-facebook", href: "https://www.facebook.com/EnDemocraciaBolivia", align: right}
    - {icon: "fa-twitter", href: "https://twitter.com/arufoundation?lang=es", align: right}
    - {icon: "fa-youtube", href: "https://www.youtube.com/user/ARUfoundation", align: right}
    theme: readable
    logo: logo_proy4.png
editor_options: 
  chunk_output_type: console
---

```{r echo=F,message=F,warning=T,results=F}
# Se habilitan las librerías necesarias
library(flexdashboard)
library(dplyr)
# Directorio de trabajo
load("D:/ARU/PPI USAID/_in/20oct_v2020.RData")
```

Bolivia
===================================== 

Column {data-width=1000}
-----------------------------------------------------------------------

### __DIFERENCIAS ENTRE VOTOS TOTALES Y VÁLIDOS__

A nivel de departamentos y recintos se pueden observar diferencias negativas y positivas.

Diferencias negativas implican votos ausentes, es decir, se suprimieron votos en las actas finales de un(os) determinado(s) candidato(s) a la presidencia. Por el contrario, diferencias positivas demuestran que se inflaron los votos en un determinado recinto para un(os) determinado(s) candidato(s).

```{r}
bd_computo <- pcomp %>% filter(dpais == "Bolivia") %>% group_by(ddep, dmun, drec) %>% 
  summarise(CC = sum(cc), MAS =sum(mas), PDC = sum(pdc), P21F = sum(f21),
            RESTO = sum(fpv, mts, ucs, mnr, panbol), 
            TOTAL = sum(cc, mas, pdc, f21, fpv, mts, ucs, mnr, panbol),
            VALIDOS = sum(val))

bd_computo <- bd_computo %>% mutate(DIFERENCIA = TOTAL - VALIDOS)
bd_computo <- bd_computo %>% rename(DEPARTAMENTO = ddep, MUNICIPIO = dmun, RECINTO = drec)
bd_computo <- bd_computo %>% filter(DIFERENCIA != 0)

DT::datatable(bd_computo, style = "bootstrap", fillContainer = T, 
              options = list(pageLength = 15, 
                             autoWidth = TRUE,
                             dom = 'Bfrtip',
                             buttons = c('copy', 
                                         'print'),
                             scrollX = T, 
                             selection="multiple"
              ))

```

Exterior
===================================== 

Column {data-width=1000}
-----------------------------------------------------------------------

### __DIFERENCIAS ENTRE VOTOS TOTALES Y VÁLIDOS__

```{r}
bd_computo <- pcomp %>% filter(dpais != "Bolivia") %>% group_by(dpais, dmun, drec) %>% 
  summarise(CC = sum(cc), MAS = sum(mas), PDC = sum(pdc), P21F = sum(f21),
            RESTO = sum(fpv, mts, ucs, mnr, panbol),
            TOTAL = sum(cc, mas, pdc, f21, fpv, mts, ucs, mnr, panbol),
            VALIDOS = sum(val))

bd_computo <- bd_computo %>% mutate(DIFERENCIA = TOTAL - VALIDOS)
bd_computo <- bd_computo %>% rename(PAIS = dpais, MUNICIPIO = dmun, RECINTO = drec)
bd_computo <- bd_computo %>% filter(DIFERENCIA < 0)

DT::datatable(bd_computo, style = "bootstrap", fillContainer = T, 
              options = list(pageLength = 15, 
                             autoWidth = TRUE,
                             dom = 'Bfrtip',
                             buttons = c('copy', 
                                         'print'),
                             scrollX = T, 
                             selection="multiple"
              ))
```

TREP1
===================================== 
   
Column {data-width=500}
-----------------------------------------------------------------------

### __DISTRIBUCIÓN ANTES DEL CORTE DEL TREP__

```{r}
bd_aparo <- bdaparo %>% filter(dpais == "Bolivia") %>% group_by(ddep, dmun, drec) %>% 
  summarise(CC1 = sum(cc), MAS1 = sum(mas), PDC1 = sum(pdc), P21F1 = sum(f21),
            RESTO1 = sum(fpv, mts, ucs, mnr, panbol),
            TOTAL1 = sum(cc, mas, pdc, f21, fpv, mts, ucs, mnr, panbol),
            VALIDOS1 = sum(val))

# Se efectúan pruebas para aquellas mesas dónde TOTAL == VALIDOS (sin anomalía contable)

bd_aparo1 <- bd_aparo %>% filter(TOTAL1 == VALIDOS1)
bd_aparo1[, 4:8] <- round(prop.table(as.matrix(bd_aparo1[, 4:8]),1)*100,2)

bd_dparo <- bdparo %>% filter(dpais == "Bolivia") %>% group_by(ddep, dmun, drec) %>% 
  summarise(CC2 = sum(cc), MAS2 = sum(mas), PDC2 = sum(pdc), P21F2 = sum(f21),
            RESTO2 = sum(fpv, mts, ucs, mnr, panbol),
            TOTAL2 = sum(cc, mas, pdc, f21, fpv, mts, ucs, mnr, panbol),
            VALIDOS2 = sum(val))
bd_dparo1 <- bd_dparo %>% filter(TOTAL2 == VALIDOS2)
bd_dparo1[, 4:8] <- round(prop.table(as.matrix(bd_dparo1[, 4:8]),1)*100,2)

# PRUEBA con CC: candidato perjudicado según diversas fuentes

anomala <- inner_join(bd_aparo1, bd_dparo1, by = c("ddep", "dmun", "drec"))
anomala <- anomala %>% mutate(num = ((CC1/100) - (CC2/100)))
anomala <- anomala %>% mutate(den = sqrt((((CC1/100)*(1-(CC1/100)))/TOTAL1) + (((CC2/100)*(1-(CC2/100)))/TOTAL2)))
anomala <- anomala %>% mutate(zt = num / den)
x <- qnorm(0.975, lower.tail = F)
anomala <- anomala %>% mutate(keep = if_else(between(zt, x, -x), T, F))
anomala <- anomala %>% filter(keep == F)

bd1 <- anomala %>% select(ddep, dmun, drec, CC1, MAS1, PDC1, P21F1, 
                          RESTO1, VALIDOS1)
bd1 <- bd1 %>% rename(DPTO = ddep, MUN = dmun, RECINTO = drec, 
                      CC = CC1, MAS = MAS1, PDC = PDC1, P21F = P21F1, 
                      RESTO = RESTO1, VALIDOS = VALIDOS1)
bd2 <- anomala %>% select(ddep, dmun, drec, CC2, MAS2, PDC2, P21F2, 
                          RESTO2, VALIDOS2)
bd2 <- bd2 %>% rename(DPTO = ddep, MUN = dmun, RECINTO = drec, 
                      CC = CC2, MAS = MAS2, PDC = PDC2, P21F = P21F2, 
                      RESTO = RESTO2, VALIDOS = VALIDOS2)

DT::datatable(bd1, style = "bootstrap", fillContainer = T, 
              options = list(pageLength = 15, 
                             autoWidth = TRUE,
                             dom = 'Bfrtip',
                             buttons = c('copy', 
                                         'print'),
                             scrollX = T, 
                             selection="multiple"
              ))

```

Column {data-width=500}
-----------------------------------------------------------------------

### __DISTRIBUCIÓN DESPUÉS DEL CORTE DEL TREP__

```{r}
DT::datatable(bd2, style = "bootstrap", fillContainer = T, 
              options = list(pageLength = 15, 
                             autoWidth = TRUE,
                             dom = 'Bfrtip',
                             buttons = c('copy', 
                                         'print'),
                             scrollX = T, 
                             selection="multiple"
              ))
```

TREP2
===================================== 
   
Column {data-width=500}
-----------------------------------------------------------------------

### __DISTRIBUCIÓN ANTES DEL CORTE DEL TREP: VALIDOS $\neq$ TOTAL__

```{r}

# Se efectúan pruebas para aquellas mesas dónde TOTAL != VALIDOS (sin anomalía contable)

bd_aparo2 <- bd_aparo %>% filter(TOTAL1 != VALIDOS1)
bd_aparo2[, 4:8] <- round(prop.table(as.matrix(bd_aparo2[, 4:8]),1)*100,2)

bd_dparo2 <- bd_dparo %>% filter(TOTAL2 != VALIDOS2)
bd_dparo2[, 4:8] <- round(prop.table(as.matrix(bd_dparo2[, 4:8]),1)*100,2)

# PRUEBA con CC: candidato perjudicado según diversas fuentes

anomala2 <- inner_join(bd_aparo2, bd_dparo2, by = c("ddep", "dmun", "drec"))
anomala2 <- anomala2 %>% mutate(num = ((CC1/100) - (CC2/100)))
anomala2 <- anomala2 %>% mutate(den = sqrt((((CC1/100)*(1-(CC1/100)))/TOTAL1) + (((CC2/100)*(1-(CC2/100)))/TOTAL2)))
anomala2 <- anomala2 %>% mutate(zt = num / den)
x <- qnorm(0.975, lower.tail = F)
anomala2 <- anomala2 %>% mutate(keep = if_else(between(zt, x, -x), T, F))
anomala2 <- anomala2 %>% filter(keep == F)

bd3 <- anomala2 %>% select(ddep, dmun, drec, CC1, MAS1, PDC1, P21F1, 
                          RESTO1, VALIDOS1, TOTAL1)
bd3 <- bd3 %>% rename(DPTO = ddep, MUN = dmun, RECINTO = drec, 
                      CC = CC1, MAS = MAS1, PDC = PDC1, P21F = P21F1, 
                      RESTO = RESTO1, VALIDOS = VALIDOS1, TOTAL = TOTAL1)
bd4 <- anomala2 %>% select(ddep, dmun, drec, CC2, MAS2, PDC2, P21F2, 
                          RESTO2, VALIDOS2, TOTAL2)
bd4 <- bd4 %>% rename(DPTO = ddep, MUN = dmun, RECINTO = drec, 
                      CC = CC2, MAS = MAS2, PDC = PDC2, P21F = P21F2, 
                      RESTO = RESTO2, VALIDOS = VALIDOS2, TOTAL = TOTAL2)

DT::datatable(bd3, style = "bootstrap", fillContainer = T, 
              options = list(pageLength = 15, 
                             autoWidth = TRUE,
                             dom = 'Bfrtip',
                             buttons = c('copy', 
                                         'print'),
                             scrollX = T, 
                             selection="multiple"
              ))

```

Column {data-width=500}
-----------------------------------------------------------------------

### __DISTRIBUCIÓN DESPUÉS DEL CORTE DEL TREP: VALIDOS $\neq$ TOTAL__

```{r}
DT::datatable(bd4, style = "bootstrap", fillContainer = T, 
              options = list(pageLength = 15, 
                             autoWidth = TRUE,
                             dom = 'Bfrtip',
                             buttons = c('copy', 
                                         'print'),
                             scrollX = T, 
                             selection="multiple"
              ))
```
